(function(){
const originalRenderAll=window.renderAll;
function animalOptions(){return '<option value="">Vel dyr...</option>'+data.animals.filter(isActiveAnimal).map(a=>`<option value="${esc(a.id)}">${esc(a.individnummer)} · ${esc(a.kjonn||"")} ${a.rase?'· '+esc(a.rase):''}</option>`).join('')}
function renderV3Selects(){if(typeof renderLambMotherSelect==='function')renderLambMotherSelect();if($('healthAnimal'))$('healthAnimal').innerHTML=animalOptions();if($('weightAnimal'))$('weightAnimal').innerHTML=animalOptions();if($('movePasture'))$('movePasture').innerHTML='<option value="">Vel jordlapp...</option>'+data.pastures.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}${p.area_dekar?' · '+esc(p.area_dekar)+' daa':''}</option>`).join('')}
window.loadAll=async function(options={}){
 const all=['animals','events','tasks','matings','health_records','weights','pastures','pasture_moves','diary_entries','farm_profile','supplies','bales','prices'];
 const wanted=options.tables?new Set(options.tables):new Set(all),should=n=>wanted.has(n),query=(name,orders)=>{let q=supabaseClient.from(name).select('*');for(const [field,ascending] of orders||[])q=q.order(field,{ascending});return q};
 const names=['animals','events','tasks','matings','health_records','weights','pastures','pasture_moves','diary_entries','farm_profile','supplies','bales','prices'];
 const orders={animals:[['created_at',false]],events:[['date',false],['created_at',false]],tasks:[['created_at',false]],matings:[['mating_date',false]],health_records:[['date',false],['created_at',false]],weights:[['date',false],['created_at',false]],pastures:[['name',true]],pasture_moves:[['date',false],['created_at',false]],diary_entries:[['date',false],['created_at',false]],farm_profile:[['created_at',false]],supplies:[['name',true]],bales:[['date',false],['created_at',false]],prices:[['updated_at',false],['created_at',false]]};
 const results=await Promise.all(names.map(n=>should(n)?query(n,orders[n]):Promise.resolve(null))),snapshots=Object.fromEntries(names.map((n,i)=>[n,results[i]]));
 for(const n of names){const r=snapshots[n];if(r?.error)throw new Error(`${n}: ${r.error.message}`)}
 if(snapshots.animals)data.animals=snapshots.animals.data||[];
 if(snapshots.events){const parsed=(snapshots.events.data||[]).map(row=>({row,j:parseJson(row.description)}));
  data.logs=parsed.filter(({row,j})=>j._kind!=='lamming'&&j._kind!=='plan'&&j._kind!=='paring'&&j._kind!=='slakt'&&j._kind!=='adoption'&&row.type!=='Lamming').map(({row:x,j})=>({id:x.id,date:x.date,type:x.type,note:j.note??x.description??'',animal:x.animal_id?animalNumber(x.animal_id):(j.animal||''),user:j.user||'Ukjend'}));
  data.lambings=parsed.filter(({row,j})=>j._kind==='lamming'||row.type==='Lamming').map(({row:x,j})=>({id:x.id,animalId:x.animal_id,date:x.date,mother:j.mother||animalNumber(x.animal_id),count:Number(j.count||1),note:j.note||'',user:j.user||'Ukjend',lammekode:j.lammekode||'',birthProcess:j.birthProcess||'',udderStatus:j.udderStatus||'',lambs:j.lambs||[]}));
  data.plans=parsed.filter(({j})=>j._kind==='plan').map(({row:x,j})=>({id:x.id,date:x.date,type:j.planType||'Anna',time:j.time||'',contact:j.contact||'',note:j.note||'',status:j.status||'Planlagt',user:j.user||'Ukjend'}));
  data._legacyMatings=parsed.filter(({j})=>j._kind==='paring').map(({row:x,j})=>({id:'legacy-'+x.id,date:x.date,ewe:j.ewe||animalNumber(x.animal_id),ram:j.ram||'',eweId:x.animal_id,ramId:data.animals.find(a=>a.individnummer===j.ram)?.id||null,round:Number(j.round||1),due:j.due||calcDue(x.date),note:j.note||'',user:j.user||'Ukjend'}));
  data.slaughter=parsed.filter(({j})=>j._kind==='slakt').map(({row:x,j})=>({id:x.id,date:x.date,animal:j.animal||animalNumber(x.animal_id),recipient:j.recipient||'',note:j.note||'',status:j.status||'Planlagt',sentAt:j.sentAt||'',user:j.user||'Ukjend'}));data.adoptions=parsed.filter(({j})=>j._kind==='adoption').map(({row:x,j})=>({id:x.id,lambId:j.lambId||x.animal_id,biologicalMotherId:j.biologicalMotherId||null,adoptiveMotherId:j.adoptiveMotherId||null,date:j.date||x.date,note:j.note||'',user:j.user||'Ukjend'}));
 }
 if(snapshots.tasks)data.tasks=snapshots.tasks.data||[];
 for(const [name,key] of [['health_records','health'],['weights','weights'],['pastures','pastures'],['pasture_moves','pastureMoves'],['diary_entries','diary'],['supplies','supplies'],['bales','bales'],['prices','prices']])if(snapshots[name])data[key]=snapshots[name].data||[];
 if(snapshots.farm_profile)data.farmProfile=snapshots.farm_profile.data?.[0]||null;
 if(snapshots.matings)data.matings=[...(snapshots.matings.data||[]).map(x=>({id:x.id,date:x.mating_date,ewe:animalNumber(x.ewe_id),ram:animalNumber(x.ram_id),eweId:x.ewe_id,ramId:x.ram_id,round:Number(x.mating_round||1),due:x.expected_due_date,note:x.note||'',user:x.user_name||'Ukjend'})),...(data._legacyMatings||[])];
 else if(snapshots.events)data.matings=[...data.matings.filter(x=>!String(x.id).startsWith('legacy-')),...(data._legacyMatings||[])];
 renderAll();
};
function paintSyncStatus(state){
 const el=$('syncStatus');if(!el)return;
 let message='',kind='';
 if(state.error){message=`Synkroniseringa feila. ${state.error} Kontroller nettilgang og Supabase-tilgang.`;kind='error'}
 else if(!state.online){message='Du er utan nett. Appen kan visast, men data kan ikkje lesast eller lagrast før nettet er tilbake.';kind='offline'}
 else if(state.pending){message=`${state.pending} endring${state.pending===1?'':'ar'} ventar på stadfesting frå Supabase.`;kind='pending'}
 el.hidden=!message;el.className=`sync-status ${kind}`;el.textContent=message;
}
window.addEventListener('farm-sync-state',e=>paintSyncStatus(e.detail));
window.addEventListener('online',()=>paintSyncStatus(supabaseClient.getSyncState()));
window.addEventListener('offline',()=>paintSyncStatus(supabaseClient.getSyncState()));
paintSyncStatus(supabaseClient.getSyncState());
function renderHealth(){renderV3Selects();$('healthTotal').textContent=data.health.length;$('healthList').innerHTML=data.health.length?data.health.map(x=>`<article class="health-entry"><div class="health-entry-mark" data-icon="stethoscope"></div><div class="health-entry-content"><div class="health-entry-top"><div><strong>${esc(x.type||'Helseoppføring')}</strong><div class="muted">${formatDateNo(x.date)} · ${esc(animalNumber(x.animal_id)||'Ukjent dyr')}</div></div><span class="status-pill">${esc(x.user_name||'Ukjend')}</span></div>${x.treatment?`<div class="health-entry-detail"><strong>Preparat</strong><span>${esc(x.treatment)}</span></div>`:''}${x.withdrawal_end?`<div class="health-entry-detail"><strong>Tilbakehaldstid</strong><span>Til ${formatDateNo(x.withdrawal_end)}</span></div>`:''}${x.note?`<p class="health-entry-note">${esc(x.note)}</p>`:''}${x.birth_event_id?'<span class="health-source">Automatisk registrert ved lamming</span>':''}<div class="health-entry-actions"><button class="danger-btn" onclick="deleteHealth('${x.id}')">Slett oppføring</button></div></div></article>`).join(''):'<div class="empty-large">💚 Ingen helseoppføringar enno.</div>';hydrateIcons($('healthList'))}
function renderWeights(){renderV3Selects();$('weightTotal').textContent=data.weights.length;$('weightList').innerHTML=data.weights.length?data.weights.map(x=>`<div class="row"><div><strong>⚖️ ${esc(animalNumber(x.animal_id)||'Ukjent dyr')} · ${esc(x.weight)} kg</strong><div class="muted">${formatDateNo(x.date)} · ${esc(x.type)}</div>${x.note?`<div class="subtle">${esc(x.note)}</div>`:''}</div><button class="danger" onclick="deleteWeight('${x.id}')">Slett</button></div>`).join(''):'<div class="empty">⚖️ Ingen vegingar registrert enno.</div>'}
function renderPastures(){renderV3Selects();$('pastureTotal').textContent=data.pastures.length;$('pastureList').innerHTML=data.pastures.length?data.pastures.map(x=>`<div class="card pasture-card"><div class="card-head"><div><h3>🌱 ${esc(x.name)}</h3><div class="muted">${x.area_dekar?esc(x.area_dekar)+' dekar':'Areal ikkje oppgitt'}${x.location?' · '+esc(x.location):''}</div></div><span class="status-pill ${x.status==='Beita no'?'warn':x.status==='Stengt'?'red':''}">${esc(x.status)}</span></div>${x.note?`<div class="subtle" style="margin-top:7px">${esc(x.note)}</div>`:''}<div class="mini-actions"><button class="soft-btn" onclick="cyclePastureStatus('${x.id}')">Endre status</button><button class="danger-btn" onclick="deletePasture('${x.id}')">Slett</button></div></div>`).join(''):'<div class="empty-large">🌱 Ingen jordlappar registrert enno.</div>';$('pastureMoveList').innerHTML=data.pastureMoves.length?data.pastureMoves.map(x=>{const p=data.pastures.find(y=>y.id===x.pasture_id);return `<div class="row"><div><strong>🚜 ${esc(p?.name||'Ukjent jordlapp')}</strong><div class="muted">${formatDateNo(x.date)}${x.group_name?' · '+esc(x.group_name):''}${x.animal_count!=null?' · '+esc(x.animal_count)+' dyr':''}</div>${x.note?`<div class="subtle">${esc(x.note)}</div>`:''}<div class="subtle">👤 ${esc(x.user_name||'Ukjend')}</div></div><button class="danger" onclick="deletePastureMove('${x.id}')">Slett</button></div>`}).join(''):'<div class="empty">🚜 Ingen beiteflyttingar registrert enno.</div>'}
function renderDiary(){$('diaryTotal').textContent=data.diary.length;$('diaryList').innerHTML=data.diary.length?data.diary.map(x=>`<div class="card diary-card"><div class="card-head"><div><h3>${esc(x.title)}</h3><div class="muted">${formatDateNo(x.date)} · 👤 ${esc(x.user_name||'Ukjend')}</div></div></div><div style="white-space:pre-wrap;margin-top:10px;line-height:1.55">${esc(x.text)}</div><div class="mini-actions"><button class="danger-btn" onclick="deleteDiary('${x.id}')">Slett</button></div></div>`).join(''):'<div class="empty-large">📖 Ingen dagboknotat enno.</div>'}
function renderFarmAndInventory(){
  const fp=data.farmProfile||{};
  if($('farmHomeName'))$('farmHomeName').textContent=fp.name||'Sundsteigen Gård';
  if($('farmHomeDescription'))$('farmHomeDescription').textContent=fp.description||'Sauehald, jord og arbeid på garden – samla i éi løysing.';
  if($('farmHomeMeta'))$('farmHomeMeta').textContent=[fp.location,fp.phone].filter(Boolean).join(' · ')||'Kvinnherad · Sauehald';
  if($('farmName')&&!$('farmEditCard')?.classList.contains('open-edit')){$('farmName').value=fp.name||'Sundsteigen Gård';$('farmLocation').value=fp.location||'';$('farmDescription').value=fp.description||'';$('farmPhone').value=fp.phone||'';$('farmEmail').value=fp.email||'';}
  const low=data.supplies.filter(x=>Number(x.quantity||0)<=Number(x.min_quantity||0));
  if($('homeSupplyCount'))$('homeSupplyCount').textContent=`${data.supplies.length} ${data.supplies.length===1?'vare':'varer'}`;
  if($('homeSupplyAlert'))$('homeSupplyAlert').textContent=low.length?`${low.length} påfylling${low.length===1?'':'ar'} trengst`:'Lageret ser greitt ut';
  const baleCount=data.bales.reduce((n,x)=>n+Number(x.count||0),0);
  if($('homeBaleCount'))$('homeBaleCount').textContent=`${baleCount} rundballar`;
  if($('homeBaleLocation'))$('homeBaleLocation').textContent=data.bales.length?`${data.bales.length} lagerpost${data.bales.length===1?'':'ar'}`:'Ingen lagerdata enno';
  if($('homeMatingCount'))$('homeMatingCount').textContent=`${data.matings.length} paringar`;
  const due=data.matings.map(x=>x.due).filter(Boolean).sort()[0];
  if($('homeNextDue'))$('homeNextDue').textContent=due?`Neste termin ${formatDateNo(due)}`:'Ingen registrerte terminar';
  const openTasks=data.tasks.filter(x=>!x.completed).length;
  if($('homeTaskCount'))$('homeTaskCount').textContent=`${openTasks} opne`;
  if($('homeTaskHint'))$('homeTaskHint').textContent=openTasks?`${data.tasks.filter(x=>!x.completed).slice(0,1).map(x=>x.title)[0]||'Sjå gjeremål'}`:'Ingen opne gjeremål';
  if($('moreSupplyCount'))$('moreSupplyCount').textContent=`${data.supplies.length} varer · ${baleCount} rundballar`;
  $('supplyTotal').textContent=data.supplies.length;$('baleTotal').textContent=baleCount;$('priceTotal').textContent=data.prices.length;
  $('supplyList').innerHTML=data.supplies.length?data.supplies.map(x=>{const low=Number(x.quantity||0)<=Number(x.min_quantity||0);return `<div class="inventory-row ${low?'low':''}"><div class="inventory-symbol" data-icon="${x.category==='Kraftfôr'?'bag':'leaf'}"></div><div class="inventory-main"><strong>${esc(x.name)}</strong><div class="muted">${esc(x.category||'Anna')} · ${esc(x.quantity)} ${esc(x.unit||'stk')}${x.supplier?' · '+esc(x.supplier):''}</div>${x.note?`<div class="subtle">${esc(x.note)}</div>`:''}</div><div class="inventory-side"><span class="badge ${low?'gold':''}">${low?'Påfylling':'OK'}</span><button class="danger-btn" onclick="deleteSupply('${x.id}')">Slett</button></div></div>`}).join(''):'<div class="empty-large">🧺 Ingen lagerpostar enno.</div>';
  $('baleList').innerHTML=data.bales.length?data.bales.map(x=>{const count=Number(x.count||0);return `<div class="inventory-row bale-row"><div class="inventory-symbol" data-icon="hay"></div><div class="inventory-main"><strong>${esc(x.type)} · ${count} rundball${count===1?'':'ar'}</strong><div class="muted">📍 ${esc(x.location||'Lagringsstad ikkje oppgitt')} · ${formatDateNo(x.date)}</div>${x.note?`<div class="subtle">${esc(x.note)}</div>`:''}</div><div class="inventory-side bale-controls"><button class="quantity-btn minus" ${count<=0?'disabled':''} onclick="changeBaleCount('${x.id}',-1)" aria-label="Ta ut éin rundball">−1</button><span class="quantity-value">${count}</span><button class="quantity-btn plus" onclick="changeBaleCount('${x.id}',1)" aria-label="Legg til éin rundball">+1</button><button class="danger-btn" onclick="deleteBale('${x.id}')">Slett</button></div></div>`}).join(''):'<div class="empty-large">🌾 Ingen rundballar registrert enno.</div>';
  $('priceList').innerHTML=data.prices.length?data.prices.map(x=>`<div class="inventory-row"><div class="inventory-symbol" data-icon="coins"></div><div class="inventory-main"><strong>${esc(x.name)}</strong><div class="muted">${esc(x.supplier||'Leverandør ikkje oppgitt')} · ${esc(x.unit||'eining')}</div>${x.note?`<div class="subtle">${esc(x.note)}</div>`:''}</div><div class="inventory-side"><strong class="price-big">${Number(x.price||0).toLocaleString('nb-NO',{minimumFractionDigits:2,maximumFractionDigits:2})} kr</strong><button class="danger-btn" onclick="deletePrice('${x.id}')">Slett</button></div></div>`).join(''):'<div class="empty-large">💰 Ingen prisar registrert enno. Legg inn prisane de brukar frå Felleskjøpet.</div>';
  hydrateIcons();
}
window.openFarmEditor=function(){const c=$('farmEditCard');if(!c)return;c.classList.remove('hidden');c.classList.add('open-edit');$('farmName').focus();window.scrollTo({top:Math.max(0,c.offsetTop-80),behavior:'smooth'})};
window.closeFarmEditor=function(){const c=$('farmEditCard');if(c){c.classList.add('hidden');c.classList.remove('open-edit')}};
window.showInventoryTab=function(tab){document.querySelectorAll('.inventory-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.inventory-panel').forEach(p=>p.classList.toggle('active',p.id===`inventory-${tab}`))};
window.deleteSupply=async id=>{if(shouldConfirmDelete()&&!confirm('Slette denne lagerposten?'))return;try{await requireSession();const {error}=await supabaseClient.from('supplies').delete().eq('id',id);if(error)throw error;await loadAll({tables:['supplies']});toast('Lagerposten er sletta')}catch(e){errorToast(e.message)}};
window.deleteBale=async id=>{if(shouldConfirmDelete()&&!confirm('Slette denne rundballposten?'))return;try{await requireSession();const {error}=await supabaseClient.from('bales').delete().eq('id',id);if(error)throw error;await loadAll({tables:['bales']});toast('Rundballposten er sletta')}catch(e){errorToast(e.message)}};
window.changeBaleCount=async(id,delta)=>{const x=data.bales.find(b=>b.id===id);if(!x)return;const next=Math.max(0,Number(x.count||0)+Number(delta||0));if(next===Number(x.count||0))return;try{await requireSession();const {error}=await supabaseClient.from('bales').update({count:next}).eq('id',id);if(error)throw error;await loadAll({tables:['bales']});toast(delta<0?'Éin rundball teken ut 🌾':'Éin rundball lagt til 🌾')}catch(e){errorToast('Kunne ikkje oppdatere rundballageret: '+e.message)}};
window.deletePrice=async id=>{if(shouldConfirmDelete()&&!confirm('Slette denne prisen?'))return;try{await requireSession();const {error}=await supabaseClient.from('prices').delete().eq('id',id);if(error)throw error;await loadAll({tables:['prices']});toast('Prisen er sletta')}catch(e){errorToast(e.message)}};
function renderStatistics(){
 const active=data.animals.filter(isActiveAnimal),bw=data.animals.map(x=>Number(x.fodselsvekt)).filter(x=>Number.isFinite(x)&&x>0);
 $('statActive').textContent=active.length;$('statLambs').textContent=active.filter(x=>x.kjonn==='lam').length;$('statBirthWeight').textContent=bw.length?(bw.reduce((a,b)=>a+b,0)/bw.length).toFixed(1)+' kg':'–';$('statMatings').textContent=data.matings.length;$('statHealth').textContent=data.health.length;$('statWeights').textContent=data.weights.length;$('seasonHealth').textContent=data.health.length;$('seasonWeights').textContent=data.weights.length;$('seasonSlaughter').textContent=data.slaughter.filter(x=>x.status!=='Sendt').length;$('seasonPastures').textContent=data.pastures.length;
 const ewes=active.filter(x=>x.kjonn==='søye').map(ewe=>({ewe,metrics:getEweBreedingMetrics(ewe)})).sort((a,b)=>(b.metrics.score??-1)-(a.metrics.score??-1)||String(a.ewe.individnummer).localeCompare(String(b.ewe.individnummer),'nn'));
 $('eweBreedingList').innerHTML=ewes.length?ewes.map(({ewe,metrics:m})=>{const stars=m.score===null?'–':'★'.repeat(Math.round(m.score))+'☆'.repeat(5-Math.round(m.score));const average=m.average===null?'Ikkje registrert':`${m.average.toFixed(1)} kg`;const help=m.ratedCount?`${m.assisted} av ${m.ratedCount} registrerte lammingar kravde hjelp`:'Fødselsforløp ikkje registrert';return `<article class="ewe-breeding-row"><div class="ewe-breeding-title"><button type="button" class="relation-chip" onclick="openAnimalModal('${esc(ewe.id)}')">${esc(ewe.individnummer)}</button><span class="breeding-stars" aria-label="${m.score===null?'Ingen avlsdata':`${Math.round(m.score)} av 5 stjerner`}">${stars}</span></div><div class="ewe-breeding-metrics"><span><small>SNITT FØDSELSVEKT</small><strong>${average}</strong></span><span><small>FØDSELSFORLØP</small><strong>${help}</strong></span><span><small>SISTE JURSTATUS</small><strong>${esc(m.latestUdder||'Ikkje registrert')}</strong></span></div></article>`}).join(''):'<div class="empty">Registrer søyer og lammingar for å byggje avlsoversikta.</div>';
 const rm={};data.matings.forEach(x=>rm[x.ram]=(rm[x.ram]||0)+1);const rr=Object.entries(rm).sort((a,b)=>b[1]-a[1]).slice(0,8),mx=Math.max(1,...rr.map(x=>x[1]));$('ramStats').innerHTML=rr.length?rr.map(([r,n])=>`<div class="stat-bar"><strong>Vær ${esc(r)}</strong><div class="stat-track"><div class="stat-fill" style="width:${Math.round(n/mx*100)}%"></div></div><strong>${n}</strong></div>`).join(''):'<div class="empty">Registrer paringar for å få avlsoversikt.</div>';
 const cats=[['Søyer',active.filter(x=>x.kjonn==='søye').length],['Værer',active.filter(x=>x.kjonn==='vær').length],['Lam',active.filter(x=>x.kjonn==='lam').length]],mc=Math.max(1,...cats.map(x=>x[1]));$('sexStats').innerHTML=cats.map(([n,v])=>`<div class="stat-bar"><strong>${n}</strong><div class="stat-track"><div class="stat-fill" style="width:${Math.round(v/mc*100)}%"></div></div><strong>${v}</strong></div>`).join('')
}
window.renderAll=function(){updateUserUI();updateDashboard();renderFarmAndInventory();renderAnimals();renderLambMotherSelect();renderLogs();renderTasks();renderLambs();renderPlanning();renderMatings();renderSlaughter();renderAdoptions();renderHealth();renderWeights();renderPastures();renderDiary();renderStatistics();renderActivity();$('morePlanCount').textContent=`${data.plans.filter(x=>x.status!=='Gjennomført').length} planlagde`;$('moreMatingCount').textContent=`${data.matings.length} paringar`;$('moreSlaughterCount').textContent=`${data.slaughter.filter(x=>x.status!=='Sendt').length} dyr`;$('moreHealthCount').textContent=`${data.health.length} registreringar`;$('moreWeightCount').textContent=`${data.weights.length} vegingar`;$('morePastureCount').textContent=`${data.pastures.length} jordlappar`;$('moreDiaryCount').textContent=`${data.diary.length} notat`;setActiveNav(document.querySelector('.page.active')?.id||'dashboard');applyAppSettings();updateSettingsSummary()};
async function insertV3(table,row,msg,page){await requireSession();const {error}=await supabaseClient.from(table).insert(row);if(error)throw error;await loadAll({tables:[table]});toast(msg);if(page)openPage(page)}
window.deleteHealth=async id=>{if(!confirm('Slette helseoppføringa?'))return;try{await requireSession();const {error}=await supabaseClient.from('health_records').delete().eq('id',id);if(error)throw error;await loadAll({tables:['health_records']});toast('Helseoppføringa er sletta')}catch(e){errorToast(e.message)}};
window.deleteWeight=async id=>{if(!confirm('Slette veginga?'))return;try{await requireSession();const {error}=await supabaseClient.from('weights').delete().eq('id',id);if(error)throw error;await loadAll({tables:['weights']});toast('Veginga er sletta')}catch(e){errorToast(e.message)}};
window.deletePasture=async id=>{if(!confirm('Slette jordlappen og flyttehistorikken?'))return;try{await requireSession();const {error}=await supabaseClient.from('pastures').delete().eq('id',id);if(error)throw error;await loadAll({tables:['pastures','pasture_moves']});toast('Jordlappen er sletta')}catch(e){errorToast(e.message)}};
window.deletePastureMove=async id=>{if(!confirm('Slette flytteregistreringa?'))return;try{await requireSession();const {error}=await supabaseClient.from('pasture_moves').delete().eq('id',id);if(error)throw error;await loadAll({tables:['pasture_moves']});toast('Flyttinga er sletta')}catch(e){errorToast(e.message)}};
window.deleteDiary=async id=>{if(!confirm('Slette dagboknotatet?'))return;try{await requireSession();const {error}=await supabaseClient.from('diary_entries').delete().eq('id',id);if(error)throw error;await loadAll({tables:['diary_entries']});toast('Dagboknotatet er sletta')}catch(e){errorToast(e.message)}};
window.cyclePastureStatus=async id=>{const x=data.pastures.find(p=>p.id===id);if(!x)return;const states=['Tilgjengeleg','Beita no','Kviler','Stengt'],next=states[(states.indexOf(x.status)+1)%states.length];try{await requireSession();const {error}=await supabaseClient.from('pastures').update({status:next}).eq('id',id);if(error)throw error;await loadAll({tables:['pastures']});toast(`${x.name}: ${next}`)}catch(e){errorToast(e.message)}};
function bind(id,fn){const el=$(id);if(el&&!el.dataset.v3){el.dataset.v3='1';el.addEventListener('submit',fn)}}
bind('healthForm',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const s=await requireSession(),a=data.animals.find(x=>x.id===val('healthAnimal'));if(!a)throw new Error('Vel eit dyr.');await insertV3('health_records',{animal_id:a.id,date:val('healthDate'),type:val('healthType'),treatment:val('healthTreatment').trim()||null,withdrawal_end:val('healthWithdrawal')||null,note:val('healthNote').trim(),user_id:s.user.id,user_name:data.currentUser},'Helseoppføringa er lagra 💚','health');e.target.reset();$('healthDate').value=today()}catch(e){errorToast(e.message)}finally{b.disabled=false}});
bind('weightForm',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const s=await requireSession(),a=data.animals.find(x=>x.id===val('weightAnimal')),weight=Number(val('weightValue'));if(!a)throw new Error('Vel eit dyr.');if(!Number.isFinite(weight)||weight<0)throw new Error('Skriv inn ei gyldig vekt.');await insertV3('weights',{animal_id:a.id,date:val('weightDate'),weight,type:val('weightType'),note:val('weightNote').trim()||null,user_id:s.user.id,user_name:data.currentUser},'Veginga er lagra ⚖️','weights');e.target.reset();$('weightDate').value=today()}catch(e){errorToast(e.message)}finally{b.disabled=false}});
bind('pastureForm',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const s=await requireSession();await insertV3('pastures',{name:val('pastureName').trim(),area_dekar:val('pastureArea')?Number(val('pastureArea')):null,location:val('pastureLocation').trim()||null,status:val('pastureStatus'),note:val('pastureNote').trim()||null,user_id:s.user.id,user_name:data.currentUser},'Jordlappen er lagra 🌱','pasture');e.target.reset()}catch(e){errorToast(e.message)}finally{b.disabled=false}});
bind('pastureMoveForm',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const s=await requireSession(),p=data.pastures.find(x=>x.id===val('movePasture'));if(!p)throw new Error('Vel ei jordlapp.');const {error}=await supabaseClient.from('pasture_moves').insert({pasture_id:p.id,date:val('moveDate'),group_name:val('moveGroup').trim()||null,animal_count:val('moveCount')?Number(val('moveCount')):null,note:val('moveNote').trim()||null,user_id:s.user.id,user_name:data.currentUser});if(error)throw error;const up=await supabaseClient.from('pastures').update({status:'Beita no'}).eq('id',p.id);if(up.error)throw up.error;await loadAll({tables:['pasture_moves','pastures']});toast(`Flokken er registrert på ${p.name} 🚜`);e.target.reset();$('moveDate').value=today();openPage('pasture')}catch(e){errorToast(e.message)}finally{b.disabled=false}});
bind('diaryForm',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const s=await requireSession();await insertV3('diary_entries',{date:val('diaryDate'),title:val('diaryTitle').trim(),text:val('diaryText').trim(),user_id:s.user.id,user_name:data.currentUser},'Dagboknotatet er lagra 📖','diary');e.target.reset();$('diaryDate').value=today()}catch(e){errorToast(e.message)}finally{b.disabled=false}});
bind('farmForm',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const s=await requireSession();const row={name:val('farmName').trim(),location:val('farmLocation').trim()||null,description:val('farmDescription').trim()||null,phone:val('farmPhone').trim()||null,email:val('farmEmail').trim()||null,user_id:s.user.id,user_name:data.currentUser,updated_at:new Date().toISOString()};if(data.farmProfile?.id){const {error}=await supabaseClient.from('farm_profile').update(row).eq('id',data.farmProfile.id);if(error)throw error}else{const {error}=await supabaseClient.from('farm_profile').insert(row);if(error)throw error}await loadAll({tables:['farm_profile']});closeFarmEditor();toast('Gardinfoen er lagra ✓')}catch(e){errorToast(e.message)}finally{b.disabled=false}});
bind('supplyForm',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const s=await requireSession();await supabaseClient.from('supplies').insert({name:val('supplyName').trim(),category:val('supplyCategory'),quantity:Number(val('supplyQuantity')||0),unit:val('supplyUnit').trim()||'stk',min_quantity:Number(val('supplyMin')||0),price:val('supplyPrice')?Number(val('supplyPrice')):null,supplier:val('supplySupplier').trim()||null,note:val('supplyNote').trim()||null,user_id:s.user.id,user_name:data.currentUser});await loadAll({tables:['supplies']});e.target.reset();$('supplyUnit').value='stk';$('supplyMin').value='0';toast('Lagerposten er lagra ✓')}catch(e){errorToast(e.message)}finally{b.disabled=false}});
bind('baleForm',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const s=await requireSession();await supabaseClient.from('bales').insert({type:val('baleType').trim(),count:Number(val('baleCount')),location:val('baleLocation').trim()||null,date:val('baleDate'),note:val('baleNote').trim()||null,user_id:s.user.id,user_name:data.currentUser});await loadAll({tables:['bales']});e.target.reset();$('baleDate').value=today();toast('Rundballposten er lagra ✓')}catch(e){errorToast(e.message)}finally{b.disabled=false}});
bind('priceForm',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const s=await requireSession();await supabaseClient.from('prices').insert({name:val('priceName').trim(),category:val('priceCategory').trim()||'Anna',price:Number(val('priceValue')),unit:val('priceUnit').trim()||'eining',supplier:val('priceSupplier').trim()||'Felleskjøpet',note:val('priceNote').trim()||null,updated_at:new Date().toISOString(),user_id:s.user.id,user_name:data.currentUser});await loadAll({tables:['prices']});e.target.reset();$('priceCategory').value='Kraftfôr';$('priceSupplier').value='Felleskjøpet';toast('Prisen er lagra ✓')}catch(e){errorToast(e.message)}finally{b.disabled=false}});
const SETTINGS_DEFAULTS={theme:'garden',language:'nn',compact:false,reduceMotion:false,confirmDelete:true,startPage:'dashboard',scale:100};
function getAppSettings(){try{return {...SETTINGS_DEFAULTS,...JSON.parse(localStorage.getItem('sundsteigen_settings')||'{}')}}catch{return {...SETTINGS_DEFAULTS}}}
function saveAppSettings(s){localStorage.setItem('sundsteigen_settings',JSON.stringify(s))}
function shouldConfirmDelete(){return getAppSettings().confirmDelete}
function applyAppSettings(){const s=getAppSettings();document.body.classList.toggle('theme-white',s.theme==='white');document.body.classList.toggle('theme-dark',s.theme==='dark');document.body.classList.toggle('compact-mode',!!s.compact);document.documentElement.classList.toggle('reduce-motion',!!s.reduceMotion);const scale=Math.min(200,Math.max(50,Number(s.scale)||100));document.documentElement.style.setProperty('--app-scale',String(scale/100));
  // Skaleringa blir brukt på heile mobilgrensesnittet via body.zoom, ikkje berre main.
  document.documentElement.style.setProperty('--app-scale-percent',`${scale}%`);if($('settingTheme'))$('settingTheme').value=s.theme;if($('settingLanguage'))$('settingLanguage').value=s.language;if($('settingCompact'))$('settingCompact').checked=!!s.compact;if($('settingReduceMotion'))$('settingReduceMotion').checked=!!s.reduceMotion;if($('settingConfirmDelete'))$('settingConfirmDelete').checked=!!s.confirmDelete;if($('settingStartPage'))$('settingStartPage').value=s.startPage;if($('settingScale'))$('settingScale').value=scale;if($('settingScaleValue'))$('settingScaleValue').textContent=`${scale} %`;applyLanguage(s.language)}
const LANG={nn:{search:'Søk',more:'Meir',account:'Konto',settings:'Innstillingar',settings_desc:'Tilpass utsjånad, språk og korleis appen fungerer på telefon og PC.',search_everything:'Søk i appen'},nb:{search:'Søk',more:'Mer',account:'Konto',settings:'Innstillinger',settings_desc:'Tilpass utseende, språk og hvordan appen fungerer på telefon og PC.',search_everything:'Søk i appen'}};
function applyLanguage(lang){const t=LANG[lang]||LANG.nn;document.documentElement.lang=lang==='nb'?'nb':'nn';document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(t[k]!=null)el.textContent=t[k]});const input=$('globalSearchInput');if(input)input.placeholder=lang==='nb'?'Søk etter dyr, oppgaver, paringer, dyrestell …':'Søk etter dyr, oppgåver, paringar, dyrestell …';if($('settingsSummary'))$('settingsSummary').textContent=lang==='nb'?'Tilpassa innstillingar':'Tilpassa innstillingar'}
function updateSettingsSummary(){const s=getAppSettings();const theme={garden:'Grøn',white:'Kvitt',dark:'Mørk'}[s.theme]||'Grøn';const lang=s.language==='nb'?'Bokmål':'Nynorsk';if($('settingsSummary'))$('settingsSummary').textContent=`${theme} · ${lang}${s.compact?' · Kompakt':''}`}
function openSettings(){openPage('settings');applyAppSettings()}
function bindSettings(){['settingTheme','settingLanguage','settingCompact','settingReduceMotion','settingConfirmDelete','settingStartPage','settingScale'].forEach(id=>{const el=$(id);if(!el||el.dataset.bound)return;el.dataset.bound='1';const eventName=id==='settingScale'?'input':'change';el.addEventListener(eventName,()=>{const s=getAppSettings();if(id==='settingTheme')s.theme=el.value;if(id==='settingLanguage')s.language=el.value;if(id==='settingCompact')s.compact=el.checked;if(id==='settingReduceMotion')s.reduceMotion=el.checked;if(id==='settingConfirmDelete')s.confirmDelete=el.checked;if(id==='settingStartPage')s.startPage=el.value;if(id==='settingScale')s.scale=Number(el.value)||100;if(id==='settingStartPage')localStorage.setItem('sundsteigen_start_page',el.value);saveAppSettings(s);applyAppSettings();updateSettingsSummary();if(id!=='settingScale')toast('Innstillingane er lagra ✓')})})}
window.resetAppSettings=function(){if(!confirm('Nullstille alle appinnstillingar på denne eininga?'))return;saveAppSettings({...SETTINGS_DEFAULTS});localStorage.removeItem('sundsteigen_start_page');applyAppSettings();updateSettingsSummary();toast('Innstillingane er nullstilte')}
window.showAppInfo=function(){alert('Sundsteigen Gård\n\nModerne sauehald-app for mobil og PC.\nData blir lagra i skybasen de har kopla til appen.\n\nTips: Legg appen til på startskjermen på mobilen for å bruke ho som ei PWA.')}
window.openGlobalSearch=function(){const m=$('searchModal');if(!m)return;m.classList.add('open');m.setAttribute('aria-hidden','false');hydrateIcons(m);setTimeout(()=>{$('globalSearchInput')?.focus();runGlobalSearch()},50)}
window.closeGlobalSearch=function(){const m=$('searchModal');if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}}
window.clearGlobalSearch=function(){const i=$('globalSearchInput');if(i){i.value='';i.focus()}runGlobalSearch()}
function runGlobalSearch(){const q=(val('globalSearchInput')||'').trim().toLowerCase(),box=$('globalSearchResults');if(!box)return;if(!q){box.innerHTML='<div class="empty-large">🔎 Skriv noko for å søkje.</div>';return}const results=[];data.animals.forEach(a=>{const txt=`${a.individnummer||''} ${a.oyremerke||''} ${a.rase||''} ${a.kjonn||''}`.toLowerCase();if(txt.includes(q))results.push({kind:'Dyr',title:a.individnummer||'Utan nummer',meta:`${a.kjonn||''}${a.rase?' · '+a.rase:''}`,page:'animals',id:a.id})});data.logs.forEach(x=>{if(`${x.type} ${x.note} ${x.animal}`.toLowerCase().includes(q))results.push({kind:'Dyrestell',title:x.type,meta:`${x.date} · ${x.animal||'Ingen dyr'}`,page:'logs'})});data.tasks.forEach(x=>{if(`${x.title} ${x.description||''}`.toLowerCase().includes(q))results.push({kind:'Gjeremål',title:x.title,meta:x.completed?'Utført':'Opent',page:'tasks'})});data.matings.forEach(x=>{if(`paring ${x.ram} ${x.ewe} ${x.date}`.toLowerCase().includes(q))results.push({kind:'Paring',title:`Vær ${x.ram} → søye ${x.ewe}`,meta:`${x.date} · ${x.round}. paring`,page:'mating'})});data.lambings.forEach(x=>{if(`lamming ${x.mother} ${x.date} ${x.count}`.toLowerCase().includes(q))results.push({kind:'Lamming',title:`Mor ${x.mother}`,meta:`${x.date} · ${x.count} lam`,page:'lambing'})});data.supplies.forEach(x=>{if(`${x.name} ${x.category} ${x.supplier}`.toLowerCase().includes(q))results.push({kind:'Lager',title:x.name,meta:`${x.quantity} ${x.unit||'stk'}`,page:'supplies'})});data.bales.forEach(x=>{if(`${x.type} ${x.location} ${x.note}`.toLowerCase().includes(q))results.push({kind:'Rundballar',title:`${x.count} × ${x.type}`,meta:x.location||'Utan lagringsstad',page:'supplies'})});const out=results.slice(0,20);box.innerHTML=out.length?out.map((r,i)=>`<button class="global-result" onclick="globalSearchOpenResult('${r.page}')"><span class="result-kind">${esc(r.kind)}</span><strong>${esc(r.title)}</strong><small>${esc(r.meta||'')}</small><span class="result-arrow">›</span></button>`).join(''):'<div class="empty-large">🔎 Ingen treff på dette søket.</div>'}
window.globalSearchOpenResult=function(page){closeGlobalSearch();openPage(page)}
window.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){e.preventDefault();openGlobalSearch()}if(e.key==='Escape')closeGlobalSearch()});
document.addEventListener('input',e=>{if(e.target?.id==='globalSearchInput')runGlobalSearch()});
bindSettings();
applyAppSettings();
function init(){['healthDate','weightDate','moveDate','diaryDate','baleDate'].forEach(id=>{if($(id))$(id).value=today()});try{loadAll()}catch(e){console.error(e)}}
setTimeout(init,100);
})();

// --- Sundsteigen Gård: backup + søyegruppe ---
(function(){
  const BACKUP_TABLES=['animals','events','tasks','matings','health_records','weights','pastures','pasture_moves','diary_entries','farm_profile','supplies','bales','prices'];
  function backupFilename(){const d=new Date();const pad=n=>String(n).padStart(2,'0');return `Sundsteigen_Gard_backup_${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}.json`}
  window.downloadFullBackup=async function(){
    try{
      await requireSession();
      const out={backup_version:1,app:'Sundsteigen Gård',created_at:new Date().toISOString(),tables:{}};
      for(const table of BACKUP_TABLES){const {data,error}=await supabaseClient.from(table).select('*');if(error)throw new Error(`${table}: ${error.message}`);out.tables[table]=data||[]}
      const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'});
      const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=backupFilename();document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);
      toast('Full backup er lasta ned 💾');
    }catch(e){errorToast('Kunne ikkje lage backup: '+e.message)}
  };
  window.importFullBackup=async function(ev){
    const file=ev.target.files?.[0];if(!file)return;
    try{
      await requireSession();
      const text=await file.text();const backup=JSON.parse(text);
      if(!backup?.tables?.animals || !backup?.backup_version)throw new Error('Dette ser ikkje ut som ei Sundsteigen Gård-backupfil.');
      const counts=Object.fromEntries(BACKUP_TABLES.map(t=>[t,Array.isArray(backup.tables[t])?backup.tables[t].length:0]));
      const total=Object.values(counts).reduce((a,b)=>a+b,0);
      if(!confirm(`Importere backup med ${counts.animals} dyr og ${total} registreringar totalt?\n\nEksisterande rader med same ID blir oppdaterte. Backupen slettar ikkje andre rader.`))return;
      for(const table of BACKUP_TABLES){const rows=Array.isArray(backup.tables[table])?backup.tables[table]:[];if(!rows.length)continue;for(let i=0;i<rows.length;i+=400){const chunk=rows.slice(i,i+400);const {error}=await supabaseClient.from(table).upsert(chunk,{onConflict:'id'});if(error)throw new Error(`${table}: ${error.message}`)}}
      await loadAll();toast('Backup er importert ✓');
    }catch(e){errorToast('Kunne ikkje importere backup: '+e.message)}finally{ev.target.value=''}
  };

  function syncEweGroupField(){
    const sex=$('kjonn'),wrap=$('eweGroupWrap'),field=$('dyregruppe');if(!sex||!wrap||!field)return;
    const isEwe=sex.value==='søye';wrap.style.display=isEwe?'':'none';if(!isEwe)field.value='';
  }
  const sex=$('kjonn');if(sex){sex.addEventListener('change',syncEweGroupField);setTimeout(syncEweGroupField,0)}

})();

